// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHS4ipH30oBbQoDJYUs2_WzvqRMptkck',
    appId: '1:18677855550:web:a9ebd9fb2c2f85c226286f',
    messagingSenderId: '18677855550',
    projectId: 'bengaluru-interview',
    authDomain: 'bengaluru-interview.firebaseapp.com',
    storageBucket: 'bengaluru-interview.appspot.com',
    measurementId: 'G-S168N740XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9WaW1GKUpR4vTnMeQWUegjw2lLvrW4eI',
    appId: '1:18677855550:android:76e8a0ff1892f67e26286f',
    messagingSenderId: '18677855550',
    projectId: 'bengaluru-interview',
    storageBucket: 'bengaluru-interview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHptORRHbhyd7oQyUsK_gqAEbXGj0J-7U',
    appId: '1:18677855550:ios:4946a0c2ed74749726286f',
    messagingSenderId: '18677855550',
    projectId: 'bengaluru-interview',
    storageBucket: 'bengaluru-interview.appspot.com',
    androidClientId: '18677855550-t4gu50mnpgcmpt8ogq20bjbkv7a6c12i.apps.googleusercontent.com',
    iosClientId: '18677855550-ri58d0ucrm5njic36up84na0kp228ji5.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewTaskBengaluru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHptORRHbhyd7oQyUsK_gqAEbXGj0J-7U',
    appId: '1:18677855550:ios:3381f68a22c8657026286f',
    messagingSenderId: '18677855550',
    projectId: 'bengaluru-interview',
    storageBucket: 'bengaluru-interview.appspot.com',
    androidClientId: '18677855550-t4gu50mnpgcmpt8ogq20bjbkv7a6c12i.apps.googleusercontent.com',
    iosClientId: '18677855550-ketsp1u48h39kbisno7okulk365v9hr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewTaskBengaluru.RunnerTests',
  );
}
